FROM alpine:3.5
LABEL maintainer="wush"
ENTRYPOINT [ "/bin/echo", "hi kocak" ]
# docker run lab5
# ENTRYPOINT echo "hi wush"
# docker run --entrypoint "/bin/echo" lab5:v2 "Hello, Welcome to Docker Kocak "