# Use the alpine:3.5 image as the base image
FROM alpine:3.5

# Update the package index inside the container
RUN apk update

# Add a file from a URL (http://www.vlsitechnology.org/pharosc_8.4.tar.gz) into the current directory inside the container
ADD http://www.vlsitechnology.org/pharosc_8.4.tar.gz .
