FROM nginx:alpine
LABEL maintainer="wush"

EXPOSE 8085/tcp
EXPOSE 8085/udp

CMD [ "nginx","-g","daemon off;" ]
# docker container run --rm -d --name expose-inst lab11:v1
# docker container run --rm -P -d --name expose-inst-Publish lab11:v1